# cloudbuild.yaml
serviceAccount: projects/rare-origin-458408-r0/serviceAccounts/gemini-summarizer-sa@rare-origin-458408-r0.iam.gserviceaccount.com

# backend/cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY
steps:
# 1) Build image
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - '-t'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/doc-repo/doc-summarizer:$SHORT_SHA'
  - '-f'
  - 'backend/Dockerfile'
  - 'backend/'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/doc-repo/doc-summarizer:$SHORT_SHA'
# deploy lên Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - run
  - deploy
  - doc-summarizer
  - --image=us-central1-docker.pkg.dev/$PROJECT_ID/doc-repo/doc-summarizer:$SHORT_SHA
  - --region=us-central1
  - --platform=managed
  - --allow-unauthenticated
# Khai báo image để Cloud Build “đánh dấu” thành artifact
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/doc-repo/doc-summarizer'
