# cloudbuild.yaml
serviceAccount: projects/rare-origin-458408-r0/serviceAccounts/gemini-summarizer-sa@rare-origin-458408-r0.iam.gserviceaccount.com

# backend/cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1) Build image
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-f', 'backend/Dockerfile',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/doc-repo/doc-summarizer',
      'backend'
    ]

# 2) Push image lên Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/doc-repo/doc-summarizer'
    ]

# 3) Deploy lên Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy doc-summarizer \
        --image us-central1-docker.pkg.dev/$PROJECT_ID/doc-repo/doc-summarizer \
        --region us-central1 \
        --platform managed \
        --allow-unauthenticated \
        --service-account gemini-summarizer-sa@rare-origin-458408-r0.iam.gserviceaccount.com \
        --set-env-vars GOOGLE_API_KEY=$$GOOGLE_API_KEY,GEMINI_MODEL=$$GEMINI_MODEL


# Khai báo image để Cloud Build “đánh dấu” thành artifact
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/doc-repo/doc-summarizer'
