options:
  logging: CLOUD_LOGGING_ONLY

steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/doc-summarizer','.']


- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/doc-summarizer']


- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'doc-summarizer'
    - '--image'
    - 'gcr.io/$PROJECT_ID/doc-summarizer'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/doc-summarizer'
