name: ai_doc
description: "AI Doc Summarizer Flutter App"
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  device_info_plus: ^9.1.1
  share_plus: ^7.2.1 

  # CORE FLUTTER DEPENDENCIES
  cupertino_icons: ^1.0.2

  # NETWORK & FILE
  http: ^1.2.1
  file_picker: ^10.1.9
  path_provider: ^2.1.2
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true